### PR TITLE
switch outdated ImageMagick dependency to gm module

### PR DESCRIPTION
**Pull request by sosloow**
Maybe It's better just to create another processor, since it uses GraphicsMagick binaries instead of ImageMagick? #3

### CODE REVIEW

**Comment by achingbrain** [comment]
Thanks for this - I'd been meaning to get round to doing this but never quite managed to.

I've merged your pull request and published this as [mongoose-crate-gm](npmjs.org/package/mongoose-crate-gm).

The only change I made was to use `imageMagick: true` instead of `gm: false` as an option to switch out GraphicsMagick for ImageMagick internally as my preference is for affirmatively specifying to use ImageMagick rather than just saying "Don't use GraphicsMagick" and not saying what to use instead.

Anyway thanks again.

**Comment by sosloow** [comment]
@achingbrain then you should notice in the readme, that the library is based on the GraphicsMagick's binaries, and write about imageMagick option too, or else everyone's going to use it with IM binaries (and fail https://github.com/achingbrain/mongoose-crate-gm/issues/1 ).

**Comment by achingbrain** [comment]
There's a [Using ImageMagick instead of GraphicsMagic section](https://github.com/achingbrain/mongoose-crate-gm#using-imagemagick-instead-of-graphicsmagic) at the bottom of the readme for the mongoose-crate-gm module.  Is that what you meant?

**Comment by sosloow** [comment]
Ah, I overlooked it, sorrey

**Pull request closed without merging**
